<?php

namespace ContainerRvAfHqO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HsWD_0mService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hsWD.0m' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hsWD.0m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.A0rcl1e', 'get_ServiceLocator_A0rcl1eService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\TicketController::delete' => ['privates', '.service_locator.WcPH6MX', 'get_ServiceLocator_WcPH6MXService', true],
            'App\\Controller\\TicketController::edit' => ['privates', '.service_locator.WcPH6MX', 'get_ServiceLocator_WcPH6MXService', true],
            'App\\Controller\\TicketController::index' => ['privates', '.service_locator.lURcPFt', 'get_ServiceLocator_LURcPFtService', true],
            'App\\Controller\\TicketController::show' => ['privates', '.service_locator.WcPH6MX', 'get_ServiceLocator_WcPH6MXService', true],
            'App\\Controller\\UserLoginController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.A0rcl1e', 'get_ServiceLocator_A0rcl1eService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\TicketController:delete' => ['privates', '.service_locator.WcPH6MX', 'get_ServiceLocator_WcPH6MXService', true],
            'App\\Controller\\TicketController:edit' => ['privates', '.service_locator.WcPH6MX', 'get_ServiceLocator_WcPH6MXService', true],
            'App\\Controller\\TicketController:index' => ['privates', '.service_locator.lURcPFt', 'get_ServiceLocator_LURcPFtService', true],
            'App\\Controller\\TicketController:show' => ['privates', '.service_locator.WcPH6MX', 'get_ServiceLocator_WcPH6MXService', true],
            'App\\Controller\\UserLoginController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\TicketController::delete' => '?',
            'App\\Controller\\TicketController::edit' => '?',
            'App\\Controller\\TicketController::index' => '?',
            'App\\Controller\\TicketController::show' => '?',
            'App\\Controller\\UserLoginController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\TicketController:delete' => '?',
            'App\\Controller\\TicketController:edit' => '?',
            'App\\Controller\\TicketController:index' => '?',
            'App\\Controller\\TicketController:show' => '?',
            'App\\Controller\\UserLoginController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
