<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNHe9sZt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNHe9sZt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNHe9sZt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNHe9sZt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNHe9sZt\App_KernelDevDebugContainer([
    'container.build_hash' => 'NHe9sZt',
    'container.build_id' => 'a2b7c566',
    'container.build_time' => 1598432875,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNHe9sZt');
